### ISSUE TITLE
API Zugriff bei BernMobil ?

### ISSUE THREAD

**Issue by chatelao** [BERNMOBIL/dynamo#1]
Wo könnte ich einen API-Key für den Bernmobil Server erhalten?

Merci, Olivier

**Comment by Fuchs** [comment]
Hallo Olivier, 

diese können wir üblicherweise nicht an Privatpersonen herausgeben, da es mit Lizenzen und Lizenzkosten verbunden ist. Was wäre der Verwendungszweck? 

Das Format, in dem die Daten vom Backend erwartet werden, ist im README erklärt. Es sollte möglich sein, mit etwas Code und einer Open Data Plattform wie z.B. https://opentransportdata.swiss/de/dataset  selber ein Backend zu stellen, um das hier verfügbare Frontend zu füttern.

**Comment by Fuchs** [comment]
geschlossen wegen Inaktivität
